//Search
export const SearchTypes = {
  GET_LIST: "@Search/GET_LIST",
  SET_SEARCH_VALUE: "@Search/SET_SEARCH_VALUE",
  SET_LOADING: "@Search/SET_LOADING",
  GET_DATA: "@Search/GET_DATA",
  SET_LOADING_DATA: "@Search/SET_LOADING_DATA",
  GET_TOP_TRACKS: "@Search/GET_TOP_TRACKS",
  GET_ARTIST_ALBUMS: "@Search/GET_ARTIST_ALBUMS",
  GET_ARTIST: "@Search/GET_ARTIST"
};
